#!/bin/bash
echo Generating CVs

cp de-macro/de-macro ./de-macro-script.py
for LAN in ENG GER SPA
do
echo "Generating CV in $LAN"
echo "%New Latex Temporal File" > CV_GRC_${LAN}.tex
cat ./languages/$LAN.lan >> CV_GRC_${LAN}.tex
cat base_CV_GRC.tex >> CV_GRC_${LAN}.tex
echo "Executing de macro"
#python -O de-macro-script.py CV_GRC_${LAN}_temp
pdflatex -interaction=batchmode CV_GRC_${LAN}.tex
#pdflatex -interaction=batchmode "\def\gonzalocvlanguage{$LAN}\input{CV_GRC_$LAN.tex}"
#rm CV_GRC_${LAN}.tex
rm CV_GRC_${LAN}.out
rm CV_GRC_${LAN}.log
rm CV_GRC_${LAN}.aux

done
